<br /><br />
<div id="view-content">
	<p>View script for controller <b>Guestbook</b> and script/action name <b>index</b></p>
</div>

<?php
  if ($this->identity == null) { ?>
    <p>Aby się zalogować <a href="/uzytkownicy/login">kliknij tutaj</a></p>
  <?php } else { ?>
    <p>Witaj <strong><?php echo $this->identity->imie; ?></strong></p>
    <p>Aby się wylogować <a href="/uzytkownicy/logout">kliknij tutaj</a></p>
  <?php } ?>

<p><a href="<?php echo $this->url(
    array(
        'controller' => 'guestbook',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>
 
Guestbook Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->email) ?></dt>
    <dd><?php echo $this->escape($entry->comment) ?></dd>
    <?php endforeach ?>
</dl>