<br /><br />
<div id="view-content">
	<p>View script for controller <b>Seo</b> and script/action name <b>index/manage </b></p>
        
    <a href="<?php echo $this->url(
    array(
        'controller' => 'seo',
        'action'     => 'add'
    ),
    'default',
    true) ?>">Add new Seo</a>

        
<table border="1" bordercolor="FFCC00" style="background-color:FFFFCC" width="400" cellpadding="3" cellspacing="3">
    
        <?php foreach ($this->entries as $entry): ?>
</dl>    
    
	<tr>
		<td><?php echo $this->escape($entry->jezyk_kod) ?></td>
		<td><?php echo $this->escape($entry->seourl) ?></td>
		<td><?php echo $this->escape($entry->zendurl)?></td>
		<td><?php echo $this->escape($entry->anchor) ?></td>
		<td><?php echo $this->escape($entry->aktywny)?></td>
  		<td><?php echo $this->escape($entry->router) ?></td>
		<td><?php echo $this->escape($entry->label)?></td>
    <?php 
    
            if($this->identity != null) 
            {

            if ($this->acl->isAllowed($this->identity->role, null, 'editSeo')) 
            {
                ?>

            <td>
           
    <a href="<?php echo $this->url(
    array(
        'controller' => 'seo',
        'action'     => 'edit',
        'id'         => $entry->id
    ),
    'default',
    true) ?>">Edit</a>
            </td>

            <?php } 
        } ?>
        
    <?php 
            if($this->identity != null) 
            {

            if ($this->acl->isAllowed($this->identity->role, null, 'deleteSeo')) 
            {
                ?>
        <td>
    <a href="<?php echo $this->url(
    array(
        'controller' => 'seo',
        'action'     => 'remove',
        'id'         => $entry->id
    ),
    'default',
    true) ?>">Remove</a>
        </td>
            <?php }
        } ?>
        </tr>
    <?php endforeach ?>        
        
</table>
        
<p><a href="<?php echo $this->url(
    array(
        'controller' => 'guestbook'
//        'action'     => 'return'
    ),
    'default',
    true) ?>">Return to guestbook</a></p>

        
<p style="font-family:verdana,arial,sans-serif;font-size:10px;"><a href="http://www.quackit.com/html/html_table_tutorial.cfm" target="_top">HTML Tables</a></p>



</div>