<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>
    
    
<?php
  if ($this->identity == null) { ?>
    
    <p>Witaj samotny wędrowcze. Aby się zalogować <a href="<?php
    echo $this->url(
            array(
        'controller' => 'login',
        'action' => 'login'
            ), 'default', true)
    ?>">kliknij tutaj</a></p>
  <?php 
  
  } else { ?>
<p>Witaj <strong><?php echo $this->identity->real_name; ?></strong> Znany jako: <strong><?php echo $this->identity->username; ?></strong></p>
 <?php // print_r($this->identity);?>

    
    <p>Aby się wylogować <a href="<?php
    echo $this->url(
            array(
        'controller' => 'login',
        'action' => 'logout'
            ), 'default', true)
    ?>">kliknij tutaj</a></p>
    
  <?php } ?>    

    <h3>This is your project's main page and what </h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
<!--            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>-->
            <a href=guestbook>Guest Book</a> |
            
        </p>
    </div>
</div>